#!/usr/bin/env node
/* ============================================================
   Writes public/js/env.js from the environment.

   This is the entire "build" for the project. Vercel runs it via the
   buildCommand in vercel.json; locally run `npm run build` after filling in
   a .env file. The output is gitignored — it holds project-specific values,
   not secrets (the anon key is a public credential protected by RLS).
   ============================================================ */

'use strict';

const fs = require('fs');
const path = require('path');
const { resolveConfig } = require('../supabase/config');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'public', 'js', 'env.js');

const { url, anonKey, problems } = resolveConfig({ root: ROOT });
const strict = process.argv.includes('--strict') || process.env.VERCEL === '1';

if (problems.length) {
  const msg = problems.map(p => '  · ' + p).join('\n');
  if (strict) {
    console.error('\n✖ Cấu hình Supabase không hợp lệ:\n' + msg +
      '\n\n  Đặt SUPABASE_URL và SUPABASE_ANON_KEY trong Environment Variables' +
      '\n  (Vercel → Project → Settings → Environment Variables) rồi deploy lại.\n');
    process.exit(1);
  }
  console.warn('\n⚠ Bỏ qua việc sinh env.js:\n' + msg +
    '\n  App sẽ hiện màn hình cấu hình để bạn nhập tay.\n');
  // Still emit a stub so the <script> tag does not 404 in local dev.
}

const banner = '/* GENERATED by scripts/generate-env.js — do not edit, do not commit. */';
const payload = {
  SUPABASE_URL: problems.length ? '' : url,
  SUPABASE_ANON_KEY: problems.length ? '' : anonKey,
  /* Stamped into the service worker URL (`/sw.js?v=…`). A new deploy is then a
     new script to the browser, which is what makes it install and drop the
     previous cache — otherwise users would sit on the old bundle forever. */
  /* Where the browser build actually lives. The APK needs it: its own origin
     is https://localhost, which cannot receive a password-reset link. */
  SITE_URL: (process.env.SITE_URL || process.env.VERCEL_PROJECT_PRODUCTION_URL || '')
    .replace(/^(?!https?:\/\/)(.+)$/, 'https://$1').replace(/\/+$/, ''),
  BUILD: process.env.VERCEL_GIT_COMMIT_SHA
    ? process.env.VERCEL_GIT_COMMIT_SHA.slice(0, 12)
    : new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)
};

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, `${banner}\nwindow.__ENV__ = ${JSON.stringify(payload, null, 2)};\n`, 'utf8');

const shown = payload.SUPABASE_URL || '(trống — sẽ dùng màn hình cấu hình)';
console.log(`✓ public/js/env.js  →  ${shown}`);
